export const exhibitionWorks = [
  {
    id: 'human-creator',
    collectionId: 'exhibition',
    order: 10,
    titleEn: 'The Human Creator',
    titleHe: 'האדם היוצר',
    image: 'assets/human-creator.jpg',
    statusEn: 'In exhibition',
    statusHe: 'בתערוכה',
    meta: 'Fine Art Canvas • 40×60 cm',
    descriptionEn: 'Every creation begins with a question. The human being does not merely discover the world — he also gives it meaning.',
    descriptionHe: 'כל יצירה מתחילה בשאלה. האדם אינו רק מגלה את העולם — הוא גם מעניק לו משמעות.',
    collectorLabelEn: 'Original Artwork',
    collectorLabelHe: 'יצירה מקורית',
    availabilityEn: 'Available',
    availabilityHe: 'זמינה',
    available: true,
    price: '₪3,400',
  },
  {
    id: 'gaze-of-compassion',
    collectionId: 'exhibition',
    order: 20,
    titleEn: 'A Gaze of Compassion',
    titleHe: 'מבט של חמלה',
    image: 'assets/compassion.jpg',
    statusEn: 'In exhibition',
    statusHe: 'בתערוכה',
    meta: 'Fine Art Canvas • 40×60 cm',
    descriptionEn: 'Sometimes the soul reveals itself in a quiet encounter where words are no longer needed.',
    descriptionHe: 'לעיתים הנשמה מתגלה דווקא במפגש שקט, שבו אין צורך במילים.',
    collectorLabelEn: 'Original Artwork',
    collectorLabelHe: 'יצירה מקורית',
    availabilityEn: 'Available',
    availabilityHe: 'זמינה',
    available: true,
    price: '₪3,400',
  },
  {
    id: 'inner-light',
    collectionId: 'exhibition',
    order: 30,
    titleEn: 'The Light Within',
    titleHe: 'האור שבפנים',
    image: 'assets/inner-light.jpg',
    statusEn: 'In exhibition',
    statusHe: 'בתערוכה',
    meta: 'Fine Art Canvas • 40×60 cm',
    descriptionEn: 'Only when a person dares to look within does he discover that the light he sought was always inside him.',
    descriptionHe: 'רק כאשר האדם מעז להביט פנימה, הוא מגלה שהאור שחיפש תמיד היה בתוכו.',
    songId: 'yofi',
    collectorLabelEn: 'Original Artwork',
    collectorLabelHe: 'יצירה מקורית',
    availabilityEn: 'Available',
    availabilityHe: 'זמינה',
    available: true,
    price: '₪3,600',
  },
  {
    id: 'hidden-harmony',
    collectionId: 'exhibition',
    order: 40,
    titleEn: 'The Hidden Harmony',
    titleHe: 'ההרמוניה הנסתרת',
    image: 'assets/hidden-harmony.jpg',
    statusEn: 'In exhibition',
    statusHe: 'בתערוכה',
    meta: 'Fine Art Canvas • 40×60 cm',
    descriptionEn: 'Science, nature, music and art speak in different languages about the same order.',
    descriptionHe: 'המדע, הטבע, המוזיקה והאמנות מדברים בשפות שונות על אותו סדר.',
    songId: 'lihyot',
    collectorLabelEn: 'Original Artwork',
    collectorLabelHe: 'יצירה מקורית',
    availabilityEn: 'Available',
    availabilityHe: 'זמינה',
    available: true,
    price: '₪3,900',
  },
  {
    id: 'fragility-of-love',
    collectionId: 'exhibition',
    order: 50,
    titleEn: 'The Fragility of Love',
    titleHe: 'שבריריות האהבה',
    image: 'assets/fragility-of-love.jpg',
    statusEn: 'From the complete cycle',
    statusHe: 'מתוך הסדרה המלאה',
    meta: '',
    descriptionEn: 'Love asks for tenderness. Sometimes its fragility is precisely what gives it strength.',
    descriptionHe: 'אהבה מבקשת עדינות. לפעמים דווקא השבריריות היא שמעניקה לה את כוחה.',
    collectorLabelEn: 'Work from the Series',
    collectorLabelHe: 'יצירה מתוך הסדרה',
    availabilityEn: 'Not offered in this exhibition',
    availabilityHe: 'לא מוצעת למכירה בתערוכה זו',
    available: false,
    price: '',
  },
  {
    id: 'gate-to-infinity',
    collectionId: 'exhibition',
    order: 60,
    titleEn: 'The Gate to Infinity',
    titleHe: 'השער אל האינסוף',
    image: 'assets/gate-to-infinity.jpg',
    statusEn: 'From the complete cycle',
    statusHe: 'מתוך הסדרה המלאה',
    meta: '',
    descriptionEn: 'Even when the secret seems close to resolution, another horizon of mystery remains.',
    descriptionHe: 'גם כאשר נדמה שהסוד קרוב לפתרון, תמיד נשאר אופק נוסף של מסתורין.',
    collectorLabelEn: 'Work from the Series',
    collectorLabelHe: 'יצירה מתוך הסדרה',
    availabilityEn: 'Not offered in this exhibition',
    availabilityHe: 'לא מוצעת למכירה בתערוכה זו',
    available: false,
    price: '',
  },
];
