// Foundation data for Pearls of Truth. A song is referenced by id, so the
// same musical interpretation can accompany several separate works.
export const pearlsOfTruthWorks = [
  {
    id: 'beauty-as-power',
    collectionId: 'pearls-of-truth',
    order: 10,
    titleEn: 'Beauty Is a Mighty Force',
    titleHe: 'יופי הוא כוח עצום',
    image: 'assets/cover-lachayot.jpg',
    video: '/assets/yofi-hover.mp4',
    descriptionEn: 'A reflection on beauty as a force that softens the soul and changes the way we see.',
    descriptionHe: 'הרהור על יופי ככוח שמרכך את הנשמה ומשנה את האופן שבו אנו רואים.',
    available: false,
    price: '',
  },
  {
    id: 'the-light-within-pearl',
    collectionId: 'pearls-of-truth',
    order: 20,
    titleEn: 'The Light Within',
    titleHe: 'האור שבפנים',
    image: 'assets/inner-light.jpg',
    video: '',
    descriptionEn: 'The light we seek outside may already be alive within us.',
    descriptionHe: 'ייתכן שהאור שאנו מחפשים בחוץ כבר חי בתוכנו.',
    available: false,
    price: '',
  },
  {
    id: 'to-live',
    collectionId: 'pearls-of-truth',
    order: 30,
    titleEn: 'To Live',
    titleHe: 'לחיות',
    image: 'assets/cover-yofi.jpg',
    video: '/assets/lachayot-hover.mp4',
    descriptionEn: 'A choice to keep living, creating and searching for light when reality fractures.',
    descriptionHe: 'בחירה להמשיך לחיות, ליצור ולחפש אור גם כשהמציאות נשברת.',
    available: false,
    price: '',
  },
];
